#!/bin/bash
set -o allexport
echo "setup_dune_bsm v0.1"

# check whether proper argument is given by user or not.
if [ "$1" == "" ]
then
  echo "[ERROR] Specify which environment you want to configure"
  echo "List of available commands:"
  echo ". setup_dune_bsm ldm"
  echo ". setup_dune_bsm sterile"
  echo ". setup_dune_bsm cafana"
  echo ". setup_dune_bsm hnl"
  echo ". setup_dune_bsm nsi"
  echo "script terminated by error"
  exit 1
fi

# check whether setup_dune.sh is configured.
if [ "$SYSTEMATICSTOOLS_LIB" == "" ]
then
  export MYENV="dune"
  source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
fi

if [ "$1" == "ldm" ]
then
  source ldm.sh
elif [ "$1" == "sterile" ]
then
  source sterile.sh
elif [ "$1" == "cafana" ]
then
  source cafana.sh
elif [ "$1" == "trident" ]
then
  source trident.sh
elif [ "$1" == "hnl" ]
then
  source hnl.sh
elif [ "$1" == "nsi" ]
then
  source nsi.sh
elif [ "$1" == "nutau" ]
then
  source nutau.sh
else
  echo "[ERROR] Can't find $1 in the valid argument list"
fi
set +o allexport
