#!/bin/bash
set -o allexport
echo "setup_dune_bsm v0.1"

if [ "$1" == "" ]
then
  echo "[ERROR] Specify which environment you want to configure"
  exit 1
fi

if [ "$1" == "ldm" ]
then
  source ldm.sh
elif [ "$1" == "sterile" ]
then
  source sterile.sh
elif [ "$1" == "cafana" ]
then
  source cafana.sh
elif [ "$1" == "trident" ]
then
  source trident.sh
elif [ "$1" == "hnl" ]
then
  source hnl.sh
elif [ "$1" == "nsi" ]
then
  source nsi.sh
elif [ "$1" == "nutau" ]
then
  source nutau.sh
else
  echo "[ERROR] Can't find $1 in the valid argument list"
fi
set +o allexport
